### ISSUE TITLE
Combine tukui's two responses to a single .json

### ISSUE THREAD

**Issue by casperstorm** [ajour/ajour-catalog#1]
In Ajour we have a concept of `flavors`. There are currently two flavors: `classic` and `retail`. A specific addon is created for one of the two flavors, but the bigger addons has a version to each flavor.

In the Catalog view of Ajour we will have two install buttons on each addon: `[ classic ]`  `[ retail ]`. Then when we press either of the buttons we know which addon to request from the API.

So, in order to show those two buttons we need to know what flavor a addon has. For the `curse` I have done the mapping:

https://github.com/casperstorm/ajour-catalog/blob/6324ff49390ae36ba69fdae87206878e9159b9b0/curse.sh#L18

Each addon will now have:

```json
    "flavors": [
      "wow_classic",
      "wow_retail"
    ]
```

So in the above case this specific addon exists in two version, one for each flavor. For the curse api it was simple because it was nested together with some other info, but for tukui api its a bit different. They have two endpoints, one for each flavor:

retail: https://www.tukui.org/api.php?addons=all
classic: https://www.tukui.org/api.php?classic-addons=all

retail_response[0]:
```json
{
	"id": "3",
	"name": "AddOnSkins",
	"small_desc": "Skins for AddOns",
	"author": "Azilroka",
	"version": "4.44",
	"screenshot_url": "https://www.tukui.org/addons/Azilroka/1503198132/screenshot.png",
	"url": "https://www.tukui.org/addons.php?download=3",
	"category": "Skins",
	"downloads": "1370208",
	"lastupdate": "2020-07-13 01:36:31",
	"patch": "8.3",
	"web_url": "https://www.tukui.org/addons.php?id=3",
	"last_download": "2020-10-03 18:41:31",
	"changelog": "https://www.tukui.org/addons.php?id=3&changelog",
	"donate_url": "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=TENQSTDX5SEWE"
}
```
classic_response[0].
```json
{
	"id": "3",
	"name": "AddOnSkins",
	"small_desc": "Skins for Blizzard UI & AddOns",
	"author": "Azilroka",
	"version": "4.44",
	"screenshot_url": "https://www.tukui.org/addons/Azilroka/1565734166/screenshot.png",
	"url": "https://www.tukui.org/classic-addons.php?download=3",
	"category": "Skins",
	"downloads": "149659",
	"lastupdate": "2020-07-13 01:38:12",
	"patch": "1.13.5",
	"web_url": "https://www.tukui.org/classic-addons.php?id=3",
	"last_download": "2020-10-03 18:25:03",
	"donate_url": "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=TENQSTDX5SEWE"
}
```

So in above example we found a addon which is avaiable for both flavors, so in that case we should map that to:

```json
{
	"id": 3,
	"name": "AddOnSkins",
	"summary": "Skins for AddOns",
	"numberOfDownloads": 1370201,
	"categories": ["Skins"],
	"source": "tukui",
        "flavors": ["wow_retail", "wow_classic"],
}
```

**Comment by petergam** [comment]
This is actually a bit more challenging than first anticipated since we cannot simply use the `id` as a unique identifier across the two feeds. Consider for instance the addon with id `9` from the two feeds below. There are clearly not the same addon.


```
{
	"id": "9",
	"name": "ElvUI Nuts and Bolts",
...
}
```

```
{
	"id": "9",
	"name": "Tukui Custom Action Bar Layout",
...
}
```

Also consider the two addons below which are the same but where the ids and names are different.

```
{
	"id": "36",
	"name": "AlysiaUI_Classic",
...
}
```

```
{
	"id": "156",
	"name": "AlysiaUI",
...
}
```

Depending on how important it is for the user experience that we are able to group the same addon I think we have different options.

* Group if name and id is identical: This is currently only true for addon with id `3`.
* Group if name is same (or almost same): This would probably be tricky to get right and would require that we add the fields for the client to know what the `retail` and `classic` ids are since they might be different
* Never try to group: This will simply just merge the to feeds and addons will never be grouped

What do you think @casperstorm?

**Comment by casperstorm** [comment]
This seems way to complicated yeah @petergp - let's not try to do any crazy logic in this api but rather just group them as you say in 3. Then let's just add flavor ["wow_retail"] for the retail ones and ["wow_classic"] for the classic once. Don't you also think this is the best approach?

**Comment by petergam** [comment]
I agree that is the best we can do now. I think we would need a more complicated data structure if we wanted to group them since the kind also have it own download number etc.
